# Assignment - 3

### Task - 1

1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [9]:
def func(n,d):
    try:
        return n/d
    except:
         print('Error occured')
        
print(func(5,0))

Error occured
None


2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"] 

verbs=["play","watch"] 

objects=["Baseball","Cricket"]

In [5]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

sentences = [sub+" "+verb+" "+obj for sub in subjects for verb in verbs for obj in objects]
for sentence in sentences:
    print(sentence)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task - 2

1. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [51]:
def vander(a,n,inc=False):
    if(inc):
        return [[num**(i) for i in range(n) ] for num in a ]
    else:
        return [[num**(n-i-1) for i in range(n) ] for num in a ]

In [52]:
vender([1,2,4,6],4)

[[1, 1, 1, 1], [8, 4, 2, 1], [64, 16, 4, 1], [216, 36, 6, 1]]

In [53]:
vender([1,2,4,6],4,True)

[[1, 1, 1, 1], [1, 2, 4, 8], [1, 4, 16, 64], [1, 6, 36, 216]]

### Using numpy

In [54]:
import numpy as np

In [55]:
np.vander([1,2,4,6],4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

In [56]:
np.vander([1,2,4,6],4,True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   6,  36, 216]])

### funtion using numpy

In [60]:
def vander_np(a,n,inc=False):
    if(inc):
        return np.array([[num**(i) for i in range(n) ] for num in a ])
    else:
        return np.array([[num**(n-i-1) for i in range(n) ] for num in a ])

In [61]:
vander_np([1,2,4,6],4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [216,  36,   6,   1]])

In [62]:
vander_np([1,2,4,6],4,True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   4,  16,  64],
       [  1,   6,  36, 216]])